name: Update members

on:
  push:
    branches: [main]
    paths:
      - 'members.yaml'

  workflow_dispatch:

jobs:
  update-members:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: codingpot/github-org-member-manage-action@v1
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          members_filepath: members.yaml
          mode: sync
